language: node_js
node_js:
    - "stable"
script:
    - npm run-script bundle
    - npm run-script lint
    - npm run-script unit-test
branch:
    only:
    - master
    - develop
deploy:
    provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    on:
        branch: master
notifications:
    email:
        on_success: change
        on_failure: always