language: node_js
node_js:
    - "stable"
branch:
    only:
    - master
    - develop
deploy:
    provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    on:
        branch: master